# Ogai image board configuration

Base_path = #insert git cloned directory 

Boards = ["ot"]

#below has not been implemented yet 

Descs = ["Off Topic"]

Max_request_size = 11     #in MB

Max_characters = 10000

Themes = ["Burichan"]     #Default included by default 

Max_thumbnail_dim = 200

Read_connection_multiplier = 5          